export enum ValidationError {
	NO_DATA = 'NO_DATA',
	INCORRECT_FIRST_NAME = 'INCORRECT_FIRST_NAME',
	INCORRECT_LAST_NAME = 'INCORRECT_LAST_NAME',
	INCORRECT_CITY = 'INCORRECT_CITY',
	INCORRECT_AGE = 'INCORRECT_AGE',
	INCORRECT_COUNTRY = 'INCORRECT_COUNTRY',
	INCORRECT_USERNAME = 'INCORRECT_USERNAME',
	INCORRECT_AVATAR = 'INCORRECT_AVATAR',
	INCORRECT_EMAIL = 'INCORRECT_EMAIL',
	INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
	INCORRECT_CURRENCY = 'INCORRECT_CURRENCY',

	INCORRECT_DATA = 'INCORRECT_DATA',
}
